export const DEFAULT_EVENTS = [
  {
    id: 'code-kshetra',
    slug: 'code-kshetra',
    name: 'CODE KSHETRA',
    hook: '24-HOUR HACKATHON',
    description: 'The ultimate 24-hour endurance hackathon. Build innovative AI, web3, or software solutions under intense pressure.',
    longDescription: 'Code Kshetra is Tech Kurukshetra flagship 24-hour hackathon bringing together software engineers, designers, and innovators to solve real-world industry challenges.',
    iconName: 'Code2',
    prize: '₹50,000',
    difficulty: 'Pro',
    category: 'Coding',
    isTechnical: true,
    type: 'Hackathon',
    rules: [
      'Teams must consist of 2 to 4 members.',
      'All code must be written during the 24-hour event duration.',
      'Use of open-source frameworks and libraries is allowed.',
      'Mentors will be present throughout the night for guidance.',
    ],
    eligibility: 'Open to all undergraduate and postgraduate students.',
    teamSize: '2-4',
    duration: '24h',
    sponsorName: 'VERCEL',
    color: 'text-primary',
  },
  {
    id: 'robo-yuddha',
    slug: 'robo-yuddha',
    name: 'ROBO YUDDHA',
    hook: 'BOT COMBAT & MAZE NAVIGATOR',
    description: 'Custom battle-bots and autonomous maze-solving robots battle for arena supremacy. May the best machine win.',
    longDescription: 'Robo Yuddha puts mechanical hardware and embedded software engineering to the test in high-impact bot combat and precision maze navigation.',
    iconName: 'Bot',
    prize: '₹35,000',
    difficulty: 'Advanced',
    category: 'Hardware',
    isTechnical: true,
    type: 'Robotics',
    rules: [
      'Bot weight must not exceed 15 kg for combat category.',
      'Wired and wireless remote controllers are allowed.',
      'Robots must comply with safety checks prior to arena entry.',
    ],
    eligibility: 'Open to engineering and technology students.',
    teamSize: '1-4',
    duration: '6h',
    sponsorName: 'ARDUINO',
    color: 'text-primary',
  },
  {
    id: 'vanguard-esports',
    slug: 'vanguard-esports',
    name: 'VANGUARD ESPORTS',
    hook: 'VALORANT & BGMI LAN FINALS',
    description: 'High-stakes tactical FPS and battle royale tournament on custom LAN servers with live shoutcasting.',
    longDescription: 'Vanguard Esports brings competitive gaming to the main stage. Battle through qualifiers to reach the auditorium LAN finals with live shoutcasting.',
    iconName: 'Gamepad2',
    prize: '₹25,000',
    difficulty: 'Intermediate',
    category: 'Gaming',
    isTechnical: false,
    type: 'Esports',
    rules: [
      'Tournament format: Single elimination qualifiers, Best of 3 finals.',
      'Standard competitive rulesets for BGMI and Valorant apply.',
      'Players must use provided tournament devices or approved setups.',
    ],
    eligibility: 'Open to all registered festival attendees.',
    teamSize: '4-5',
    duration: '8h',
    sponsorName: 'RED BULL',
    color: 'text-accent',
  },
  {
    id: 'tech-chanakya',
    slug: 'tech-chanakya',
    name: 'TECH CHANAKYA',
    hook: 'ULTIMATE TECH QUIZ',
    description: 'Rapid-fire technical trivia, system architecture puzzles, and IT history challenges against the elite.',
    longDescription: 'Test your breadth and depth of computer science knowledge, tech industry trivia, and algorithmic problem-solving in a fast-paced quiz format.',
    iconName: 'Brain',
    prize: '₹15,000',
    difficulty: 'Beginner',
    category: 'Non-Technical',
    isTechnical: false,
    type: 'Quiz',
    rules: [
      'Prelims: 30-minute written/digital round.',
      'Finals: On-stage buzzer round with negative marking.',
      'Mobile phones and external aids strictly prohibited.',
    ],
    eligibility: 'Individual participants or pairs.',
    teamSize: '1-2',
    duration: '3h',
    sponsorName: 'NOTION',
    color: 'text-accent',
  },
];

export const eventsData: any[] = DEFAULT_EVENTS;